from datetime import datetime, timezone


SEVERITY_LABELS = {"P0": "🔴 P0 - Critical", "P1": "🟠 P1 - High", "P2": "🟡 P2 - Medium", "P3": "🔵 P3 - Low", "P4": "⚪ P4 - Informational"}
PRIORITY_LABELS = {"HIGH": "🔴 HIGH", "MEDIUM": "🟡 MEDIUM", "LOW": "🟢 LOW"}
TIMELINE_ICONS = {"alert": "🚨", "action": "⚡", "escalation": "📣", "resolution": "✅", "detection": "🔍"}


def generate_markdown(postmortem: dict) -> str:
    severity = postmortem.get("severity", "P3")
    severity_label = SEVERITY_LABELS.get(severity, severity)

    lines = [
        f"# 🔥 Postmortem: {postmortem.get('title', 'Untitled Incident')}",
        "",
        f"**Severity:** {severity_label}  ",
        f"**Generated:** {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}  ",
        "**Source:** Postmortem.ai",
        "",
        "---",
        "",
        "## 📋 Executive Summary",
        "",
        postmortem.get("summary", ""),
        "",
        "---",
        "",
        "## 📅 Timeline",
        "",
        "| Time | Event | Type |",
        "|------|-------|------|",
    ]

    for entry in postmortem.get("timeline", []):
        icon = TIMELINE_ICONS.get(entry.get("type", ""), "•")
        lines.append(f"| `{entry.get('time', '')}` | {entry.get('event', '')} | {icon} {entry.get('type', '').title()} |")

    lines += [
        "",
        "---",
        "",
        "## 🔍 Root Cause Analysis",
        "",
        postmortem.get("root_cause", ""),
        "",
        "---",
        "",
        "## 💥 Impact",
        "",
    ]

    impact = postmortem.get("impact", {})
    lines += [
        f"- **Users Affected:** {impact.get('users_affected', 'Unknown')}",
        f"- **Duration:** {impact.get('duration', 'Unknown')}",
        f"- **Services Affected:** {', '.join(impact.get('services_affected', []))}",
        f"- **Revenue Impact:** {impact.get('revenue_impact', 'Unknown')}",
        "",
        "---",
        "",
        "## ⚡ Actions Taken During Incident",
        "",
    ]
    for action in postmortem.get("actions_taken", []):
        lines.append(f"- {action}")

    lines += [
        "",
        "---",
        "",
        "## ✅ Action Items",
        "",
    ]
    for item in postmortem.get("action_items", []):
        priority_label = PRIORITY_LABELS.get(item.get("priority", "MEDIUM"), item.get("priority", ""))
        lines.append(f"- **[{priority_label}]** {item.get('description', '')} *(Owner: {item.get('owner', 'TBD')})*")

    lines += [
        "",
        "---",
        "",
        "## 📖 Lessons Learned",
        "",
    ]
    for i, lesson in enumerate(postmortem.get("lessons_learned", []), 1):
        lines.append(f"{i}. {lesson}")

    lines += [
        "",
        "---",
        "",
        "## 📊 Monitoring Recommendations",
        "",
    ]
    for rec in postmortem.get("monitoring_recommendations", []):
        lines.append(f"- {rec}")

    lines += [
        "",
        "---",
        "",
        "*Generated by [Postmortem.ai](https://postmortem-ai.cubepath.app) — From chaotic logs to professional postmortems in seconds.*",
    ]

    return "\n".join(lines)
